[tox]
envlist = py310
skipsdist = True

[testenv]
deps = -rrequirements.txt
ignore_errors = True
passenv = DISPLAY
allowlist_externals = xvfb-run
commands =  python3 -m mypy -p src --strict --html-report reports/mypy
            xvfb-run python3 -m coverage run --source src -m pytest --html=reports/pytest/index.html
            python3 -m coverage html -d reports/coverage
            python3 -m flake8 --docstring-convention google --format=html --htmldir=reports/flake
            python3 -m pdoc --html --force --output-dir reports/doc .